// @title About
// @layout default
// @description About this Zest blog demo.

open Zest.Dsl

render [
    divC "about" [
        h1 [ text "About" ]
        p [ text "This is a starter blog generated by zest init. It demonstrates the native template mode: pages are written in .zest.fsx (real F#) and layouts in HTML that is automatically processed by the Nunjucks engine." ]
        p [ text "Zest pairs the safety and expressiveness of F# with a fast, zero-config static site workflow. Edit any file and run zest serve to see your changes live." ]
        p [ text "Learn more at the "; a "https://github.com/zest-ssg/zest" [ text "Zest repository" ]; text "." ]
    ]
]
