// @title About
// @layout default
// @description About this Zest blog demo.

open Zest.Dsl
open Zest.Dsl.DslSugar

render [
    h1 [ text (t "nav.about") ]

    mdDedent """
        This is a starter blog generated by `zest init`. It demonstrates
        the **native template mode**: pages are written in `.zest.fsx`
        (real F#), while layouts stay in HTML that is automatically
        processed by the Nunjucks engine.

        Zest pairs the safety and expressiveness of F# with a fast,
        zero-config static site workflow. Edit any file and run
        `zest serve` to see your changes live.

        ## Key features

        - **F# DSL** — Type-safe HTML generation with full IDE support
        - **ZCSS** — SCSS-like preprocessor with variables and color functions
        - **Multi-engine** — Nunjucks, Handlebars, HAML, Pug all supported
        - **Zero Node.js** — No npm, no webpack, no complexity

        Learn more at the [Zest repository](https://github.com/zest-ssg/zest).
    """
]
