// @title About
// @layout default
// @description About this Zest blog demo.

open Zest.Dsl

render [
    divC "about" [
        md """
# About

This is a starter blog generated by `zest init`. It demonstrates the **native
template mode**: pages are written in `.zest.fsx` (real F#), while layouts stay
in HTML that is automatically processed by the Nunjucks engine.

Zest pairs the safety and expressiveness of F# with a fast, zero-config static
site workflow. Edit any file and run `zest serve` to see your changes live.

Learn more at the [Zest repository](https://github.com/zest-ssg/zest).
"""
    ]
]
