// @title Home
// @layout default
// @description A fast, minimal blog built with Zest — where templates are real F#.

open Zest.Dsl
open Zest.Dsl.DslCollections

let recent = recent_pages 5

let postList =
    if recent.Length = 0 then
        p [ text "No posts yet — add a .zest.fsx file under content/posts/." ]
    else
        ulC "post-list" [
            for p in recent ->
                liC "post-list__item" [
                    articleC "post-card" [
                        h2C "post-card__title" [ aHref p.url p.title ]
                        (if p.date <> "" then pC "post-card__date" [ text p.date ] else "")
                        (if p.description <> "" then pC "post-card__excerpt" [ text p.description ] else "")
                    ]
                ]
        ]

render [
    divC "home" [
        sectionC "hero" [
            h1C "hero__title" [ text "Welcome to My Zest Blog" ]
            pC "hero__lead" [
                text "A fast, minimal static site generated by Zest. Pages are written in "
                code [ text ".zest.fsx" ]
                text " (real F#), and the layout is plain HTML processed by Nunjucks."
            ]
            pC "hero__lead" [
                text "Edit any file and run "
                code [ text "zest serve" ]
                text " to preview your changes live."
            ]
        ]
        sectionC "recent" [
            h2 [ text "Recent posts" ]
            postList
        ]
    ]
]
