// @title Home
// @layout home
// @description A fast, minimal blog built with Zest — where templates are real F#.

open Zest.Dsl

// The home layout renders the hero intro here plus the recent posts list,
// so this page only supplies the greeting copy.
render [
    h1 [ text "Welcome to My Zest Blog" ]
    p [
        text "A fast, minimal static site generated by Zest. Pages are written in "
        text "`.zest.fsx` (real F#), layouts in Nunjucks, styled with ZCSS."
    ]
]
