namespace Zest.Compiler.Execution
open Zest.Compiler.Model
open System
open System.Collections.Generic
open System.Globalization
open System.IO
open System.Text

// ============================================================
// FinalizeScript — evaluates _finalize.fsx at the project root after build
// ============================================================
// _finalize.fsx is the one and only post-build script, and it lives at the
// project root; it is never discovered recursively, never routed and never
// published. It runs once the site has been fully written to the output
// directory, and its responsibility is the finished output — nothing else:
//
//   inspect   — link checks, "did the build produce what it should"
//   index     — search indexes, manifests
//   reshape   — HTML/CSS/JS pretty-printing and minification
//
// Writes are confined to the output directory: writeFile refuses any path that
// would land outside `_site/`. The hook can reshape the build output but never
// the project's sources, and it cannot inject template data — that is the job
// of _prebuild.fsx, which runs before anything is rendered. Declarative
// settings stay in _config.toml.
//
// Injected context (all explicit, none magic):
//   site        : SiteInfo        site metadata from _config.toml
//   pages       : PageInfo list   every routed content page
//   build       : BuildInfo       counts, duration and output size
//   output_dir  : string          absolute path of the build output
//
// The generic helpers this hook shares with _prebuild.fsx (loadJson, loadToml,
// loadEnv, console_log, exec) are generated by ScriptHost, so a helper cannot
// mean one thing here and another there.
// ============================================================

/// One routed content page, as exposed to _finalize.fsx.
type FinalizePage = {
    /// Site-relative route, e.g. "/about/".
    Route: string
    /// Absolute path of the written file, e.g. "<root>/_site/about/index.html".
    Output: string
    /// Page title, when the source declared one.
    Title: string option
    /// Source file the page was rendered from.
    Source: string
}

/// Build statistics, as exposed to _finalize.fsx.
type FinalizeBuildInfo = {
    DurationMs: int
    PageCount: int
    AssetCount: int
    OutputBytes: int64
    StartedAt: DateTimeOffset
}

/// Result of running _finalize.fsx.
type FinalizeResult = {
    /// The script reported an error.
    HasErrors: bool
    /// Error text, empty on success.
    Errors: string list
    /// False when the script called `setFailOnError false`, asking the build
    /// to report the error without failing.
    FailOnError: bool
}

module FinalizeScript =

    /// Find `_finalize.fsx` in the project root. Exact name, root only.
    let private findFinalizeScript (rootDir: string) : string option =
        let path = Path.Combine(rootDir, FileTypes.FinalizeScriptFileName)
        if File.Exists path then Some path else None

    /// The host reads this flag file after the script exits. `setFailOnError`
    /// writes it immediately rather than at the end, so the flag still counts
    /// when the script throws before reaching its last line.
    let private readFailFlag (path: string) : bool =
        if not (File.Exists path) then true
        else
            match (File.ReadAllText path).Trim().ToLowerInvariant() with
            | "false" -> false
            | _ -> true

    /// Emit `#r` lines for the assemblies that carry the output-shaping
    /// helpers (formatHtml / minifyCss / …).
    ///
    /// Reuses DslAssembly's isolated copy — the same folder FSI already loads
    /// for every .zest.fsx page, so a second copy of the engine is never pulled
    /// into the process. Returns false (emitting nothing) when the assemblies
    /// cannot be located; the rest of the hook API still works, and a script
    /// that calls a shaping helper then fails with a plain "not defined".
    let private emitAssemblyReferences (sb: StringBuilder) : bool =
        try
            let dslPath = DslAssembly.getIsolatedDslDll ()
            let dir = Path.GetDirectoryName dslPath
            let engineDll = Path.Combine(dir, "Zest.Compiler.dll")
            let coreDll = Path.Combine(dir, "Zest.Core.dll")
            if not (File.Exists engineDll) then false
            else
                sb.AppendLine("#r @\"" + engineDll + "\"") |> ignore
                if File.Exists coreDll then
                    sb.AppendLine("#r @\"" + coreDll + "\"") |> ignore
                true
        with _ -> false

    /// Build the FSI preamble: shared helpers, injected context, then the
    /// output-shaping and error-policy switches. Everything the script can see
    /// is declared right here.
    let private buildPreamble
        (rootDir: string)
        (outputDir: string)
        (site: SiteConfig)
        (pages: FinalizePage list)
        (build: FinalizeBuildInfo)
        (failFlagFile: string)
        (doneFile: string)
        : string =

        let lit = ScriptHost.fsharpLiteral
        let optLit (v: string option) =
            match v with
            | Some s -> "Some " + lit s
            | None -> "None"

        let sb = StringBuilder()
        // `#r` directives must precede every other declaration in the script.
        let hasShaping = emitAssemblyReferences sb
        sb.AppendLine("open System") |> ignore
        sb.AppendLine("open System.IO") |> ignore
        sb.AppendLine("open System.Diagnostics") |> ignore
        sb.AppendLine("open System.Collections.Generic") |> ignore
        sb.AppendLine("open System.Text") |> ignore
        sb.AppendLine("open System.Text.Json") |> ignore
        sb.AppendLine("open System.Text.RegularExpressions") |> ignore
        // The shared helpers resolve relative paths against this.
        sb.AppendLine(sprintf "let private __projectRoot : string = %s" (lit rootDir)) |> ignore
        sb.AppendLine(ScriptHost.commonHelpersSource "_finalize") |> ignore
        sb.AppendLine() |> ignore

        // ── Injected context (read-only) ──────────────────────
        sb.AppendLine("type SiteInfo = { title: string; url: string; description: string; author: string; language: string; version: string }") |> ignore
        sb.AppendLine("type PageInfo = { route: string; output: string; title: string option; source: string }") |> ignore
        sb.AppendLine("type BuildInfo = { duration_ms: int; page_count: int; asset_count: int; output_bytes: int64; started_at: DateTimeOffset }") |> ignore
        sb.AppendLine() |> ignore

        sb.AppendLine(sprintf "let site : SiteInfo = { title = %s; url = %s; description = %s; author = %s; language = %s; version = %s }"
                          (lit site.Title) (lit site.BaseUrl) (lit site.Description)
                          (lit site.Author) (lit site.Language) (lit site.SiteVersion)) |> ignore

        sb.AppendLine("let pages : PageInfo list = [") |> ignore
        for p in pages do
            sb.AppendLine(sprintf "    { route = %s; output = %s; title = %s; source = %s }"
                              (lit p.Route) (lit p.Output) (optLit p.Title) (lit p.Source)) |> ignore
        sb.AppendLine("]") |> ignore

        // CultureInfo/DateTimeStyles are fully qualified: the generated script
        // opens only System, so an unqualified name would not resolve there.
        sb.AppendLine(sprintf "let build : BuildInfo = { duration_ms = %d; page_count = %d; asset_count = %d; output_bytes = int64 %s; started_at = DateTimeOffset.Parse(%s, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.RoundtripKind) }"
                          build.DurationMs build.PageCount build.AssetCount (string build.OutputBytes)
                          (lit (build.StartedAt.ToString("o", CultureInfo.InvariantCulture)))) |> ignore

        sb.AppendLine(sprintf "let output_dir : string = %s" (lit outputDir)) |> ignore
        sb.AppendLine(sprintf "let private __failFlagPath : string = %s" (lit failFlagFile)) |> ignore
        sb.AppendLine(ScriptHost.completionWriterSource doneFile) |> ignore
        sb.AppendLine() |> ignore

        // ── File-system helpers ───────────────────────────────
        // Reads resolve relative paths against the project root.
        sb.AppendLine("""let readFile (path: string) : string =""") |> ignore
        sb.AppendLine("""    let full = if Path.IsPathRooted path then path else Path.Combine(__projectRoot, path)""") |> ignore
        sb.AppendLine("""    File.ReadAllText full""") |> ignore
        sb.AppendLine("""let exists (path: string) : bool =""") |> ignore
        sb.AppendLine("""    let full = if Path.IsPathRooted path then path else Path.Combine(__projectRoot, path)""") |> ignore
        sb.AppendLine("""    File.Exists full || Directory.Exists full""") |> ignore
        sb.AppendLine("""let listFiles (path: string) : string list =""") |> ignore
        sb.AppendLine("""    let full = if Path.IsPathRooted path then path else Path.Combine(__projectRoot, path)""") |> ignore
        sb.AppendLine("""    if not (Directory.Exists full) then []""") |> ignore
        sb.AppendLine("""    else Directory.EnumerateFiles(full, "*", SearchOption.AllDirectories)""") |> ignore
        sb.AppendLine("""         |> Seq.map (fun f -> Path.GetRelativePath(full, f).Replace('\\', '/'))""") |> ignore
        sb.AppendLine("""         |> Seq.sort""") |> ignore
        sb.AppendLine("""         |> Seq.toList""") |> ignore
        sb.AppendLine("""let sizeOf (path: string) : int64 =""") |> ignore
        sb.AppendLine("""    let full = if Path.IsPathRooted path then path else Path.Combine(__projectRoot, path)""") |> ignore
        sb.AppendLine("""    if File.Exists full then (FileInfo full).Length""") |> ignore
        sb.AppendLine("""    elif Directory.Exists full then""") |> ignore
        sb.AppendLine("""        Directory.EnumerateFiles(full, "*", SearchOption.AllDirectories)""") |> ignore
        sb.AppendLine("""        |> Seq.sumBy (fun f -> (FileInfo f).Length)""") |> ignore
        sb.AppendLine("""    else 0L""") |> ignore
        sb.AppendLine("""let toJson (value: obj) : string =""") |> ignore
        sb.AppendLine("""    JsonSerializer.Serialize(value, JsonSerializerOptions(WriteIndented = true))""") |> ignore

        // ── writeFile — the only write, confined to the output directory ──
        sb.AppendLine("""let writeFile (path: string) (content: string) : unit =""") |> ignore
        sb.AppendLine("""    let outRoot = Path.GetFullPath output_dir""") |> ignore
        sb.AppendLine("""    let full = if Path.IsPathRooted path then Path.GetFullPath path else Path.GetFullPath(Path.Combine(outRoot, path))""") |> ignore
        sb.AppendLine("""    let prefix = outRoot.TrimEnd(Path.DirectorySeparatorChar) + string Path.DirectorySeparatorChar""") |> ignore
        sb.AppendLine("""    if not (full.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) then""") |> ignore
        sb.AppendLine("""        failwithf "_finalize.fsx may only write inside the output directory (%s); refused: %s" outRoot full""") |> ignore
        sb.AppendLine("""    let dir = Path.GetDirectoryName full""") |> ignore
        sb.AppendLine("""    if not (String.IsNullOrEmpty dir) then Directory.CreateDirectory dir |> ignore""") |> ignore
        sb.AppendLine("""    File.WriteAllText(full, content, UTF8Encoding(false))""") |> ignore
        sb.AppendLine() |> ignore

        // ── Output shaping ────────────────────────────────────
        // HTML/CSS/JS pretty-printing and minification used to be [build]
        // flags. They are post-build work here: the author decides what to
        // apply, to which files, by calling these helpers explicitly.
        if hasShaping then
            sb.AppendLine("open Zest.Compiler.Rendering") |> ignore
            sb.AppendLine("""let formatHtml (html: string) : string = Formatting.formatDefault html""") |> ignore
            sb.AppendLine("""let minifyHtml (html: string) : string = Formatting.minifySafe html""") |> ignore
            sb.AppendLine("""let formatCss (css: string) : string = Formatting.formatCss 2 css""") |> ignore
            sb.AppendLine("""let minifyCss (css: string) : string = Formatting.minifyCss css""") |> ignore
            sb.AppendLine("""let formatJs (js: string) : string = Formatting.formatJs 2 js""") |> ignore
            sb.AppendLine("""let minifyJs (js: string) : string = Formatting.minifyJs js""") |> ignore
        else
            sb.AppendLine("// Output-shaping helpers (formatHtml, minifyHtml, formatCss, minifyCss,") |> ignore
            sb.AppendLine("// formatJs, minifyJs) are unavailable: the engine assemblies could not be") |> ignore
            sb.AppendLine("// located next to this build.") |> ignore

        // Rewrite every file of one extension under the output directory.
        // Files whose transformed text is unchanged are left untouched, so a
        // no-op transform never rewrites timestamps.
        sb.AppendLine("""let rewriteFiles (extension: string) (transform: string -> string) : unit =""") |> ignore
        sb.AppendLine("""    let outRoot = Path.GetFullPath output_dir""") |> ignore
        sb.AppendLine("""    let ext = if extension.StartsWith "." then extension else "." + extension""") |> ignore
        sb.AppendLine("""    if Directory.Exists outRoot then""") |> ignore
        sb.AppendLine("""        for file in Directory.EnumerateFiles(outRoot, "*", SearchOption.AllDirectories) do""") |> ignore
        sb.AppendLine("""            if Path.GetExtension(file).Equals(ext, StringComparison.OrdinalIgnoreCase) then""") |> ignore
        sb.AppendLine("""                let text = File.ReadAllText file""") |> ignore
        sb.AppendLine("""                let updated = transform text""") |> ignore
        sb.AppendLine("""                if updated <> text then File.WriteAllText(file, updated, UTF8Encoding(false))""") |> ignore
        sb.AppendLine() |> ignore

        // ── Error policy ──────────────────────────────────────
        sb.AppendLine("""let mutable private __failOnError = true""") |> ignore
        sb.AppendLine("""let setFailOnError (value: bool) =""") |> ignore
        sb.AppendLine("""    __failOnError <- value""") |> ignore
        sb.AppendLine("    File.WriteAllText(__failFlagPath, if value then \"true\" else \"false\")") |> ignore
        sb.ToString()

    /// Run `_finalize.fsx` (if present) after the site has been written.
    /// The script is optional: a missing file is a silent no-op.
    let run
        (rootDir: string)
        (outputDir: string)
        (site: SiteConfig)
        (pages: FinalizePage list)
        (build: FinalizeBuildInfo)
        : FinalizeResult =

        let label = FileTypes.FinalizeScriptFileName
        match findFinalizeScript rootDir with
        | None -> { HasErrors = false; Errors = []; FailOnError = true }
        | Some scriptPath ->
            eprintfn "[Zest] Running _finalize.fsx..."
            let failFlagFile = ScriptHost.tempMarkerPath "finalize-flag"
            let doneFile = ScriptHost.tempMarkerPath "finalize-done"
            try
                try
                    let userScript = File.ReadAllText scriptPath
                    let preamble = buildPreamble rootDir outputDir site pages build failFlagFile doneFile
                    let source = preamble + "\n" + userScript + "\n" + ScriptHost.completionCall
                    let scriptRun = ScriptHost.runSource label doneFile source
                    let failOnError = readFailFlag failFlagFile

                    if scriptRun.Succeeded then
                        { HasErrors = false; Errors = []; FailOnError = failOnError }
                    else
                        eprintfn "[Zest] %s" scriptRun.ErrorText
                        { HasErrors = true; Errors = [ scriptRun.ErrorText ]; FailOnError = failOnError }
                with ex ->
                    let message = sprintf "%s failed: %s" label ex.Message
                    eprintfn "[Zest] %s" message
                    { HasErrors = true; Errors = [ message ]; FailOnError = true }
            finally
                try if File.Exists failFlagFile then File.Delete failFlagFile with _ -> ()
                try if File.Exists doneFile then File.Delete doneFile with _ -> ()
