namespace Zest.Compiler.Execution
open Zest.Compiler.Build
open Zest.Compiler.Model
open System
open System.Collections.Generic
open System.IO
open System.Text

// ============================================================
// PrebuildScript — evaluates _prebuild.fsx at the project root before build
// ============================================================
// _prebuild.fsx is the one and only pre-build script, and it lives at the
// project root; it is never discovered recursively. It runs as a
// `dotnet fsi` subprocess after _config.toml is loaded and before the site is
// built, and its responsibility is to shape what gets rendered — nothing else:
//
//   - addGlobal "key" value            → inject data into globalData
//   - addFilter "name" "spec"          → register a Zestucks filter pipeline
//   - addGlobalFunction "name" value   → provide a global value to templates
//
// Because F# functions can't cross the process boundary, `addFilter` takes a
// pipeline-spec string and `addGlobalFunction` takes a pre-evaluated value;
// the build pipeline registers them on the in-process template engine after
// the script exits.
//
// Deliberately absent: anything that touches the build output, and anything
// that runs after the build. That is _finalize.fsx's job. Declarative settings
// stay in _config.toml.
//
// The generic helpers this hook shares with _finalize.fsx (loadJson, loadToml,
// loadEnv, console_log, exec) are generated by ScriptHost, so a helper cannot
// mean one thing here and another there.
// ============================================================

/// Result from running _prebuild.fsx
type PrebuildResult = {
    /// Additional global data to merge into the build context.
    GlobalData: IDictionary<string, obj>
    /// Custom template filters declared via `addFilter name spec`.
    /// The spec is a Zestucks filter-pipeline string (e.g. "upper | trim")
    /// applied to the filter's input value.
    Filters: IDictionary<string, string>
    /// Global template functions declared via `addGlobalFunction name value`.
    /// Stored as pre-evaluated values (functions can't cross the process
    /// boundary, so nullary value-providing is the supported form).
    GlobalFunctions: IDictionary<string, obj>
    /// Script had errors
    HasErrors: bool
    /// Error messages (if any)
    Errors: string list
}

module PrebuildScript =

    /// Stringify any value (null-safe).
    let private toStr (v: obj) = if isNull v then "" else v.ToString()

    /// Find `_prebuild.fsx` in the project root. Exact name, root only:
    /// there is no alias and no recursive scan.
    let private findPrebuildScript (rootDir: string) : string option =
        let path = Path.Combine(rootDir, FileTypes.PrebuildScriptFileName)
        if File.Exists path then Some path else None

    /// Build the FSI preamble: shared helpers, then the three template-facing
    /// bindings, then the deferred result writer.
    let private buildPreamble (rootDir: string) (resultFile: string) =
        let sb = StringBuilder()
        sb.AppendLine("open System") |> ignore
        sb.AppendLine("open System.IO") |> ignore
        sb.AppendLine("open System.Diagnostics") |> ignore
        sb.AppendLine("open System.Collections.Generic") |> ignore
        sb.AppendLine("open System.Text.Json") |> ignore
        // The shared helpers resolve relative paths against this.
        sb.AppendLine(sprintf "let private __projectRoot : string = %s" (ScriptHost.fsharpLiteral rootDir)) |> ignore
        sb.AppendLine(ScriptHost.commonHelpersSource "_prebuild") |> ignore
        sb.AppendLine(ScriptHost.stateDeclaration) |> ignore
        // addGlobal — adds a key-value pair to global data
        sb.AppendLine("""let addGlobal (key: string) (value: obj) = __scriptState.[key] <- value""") |> ignore
        // addFilter — register a custom template filter by pipeline spec.
        // Since F# functions can't cross the process boundary, the spec is a
        // Zestucks filter-pipeline string (e.g. "upper | trim") that the
        // engine applies to the filter's input value.
        sb.AppendLine("""let addFilter (name: string) (spec: string) = __scriptState.["__filter:" + name] <- box spec""") |> ignore
        // addGlobalFunction — provide a global value to templates. Stored
        // pre-evaluated; nullary value-providing is the supported form.
        sb.AppendLine("""let addGlobalFunction (name: string) (value: obj) = __scriptState.["__gfn:" + name] <- value""") |> ignore
        // Deferred result serialization function
        sb.AppendLine(ScriptHost.resultWriterSource resultFile) |> ignore
        sb.ToString()

    /// Empty PrebuildResult (used when no script or on early failure).
    let private emptyResult : PrebuildResult =
        { GlobalData = dict [] :> IDictionary<string, obj>
          Filters = dict [] :> IDictionary<string, string>
          GlobalFunctions = dict [] :> IDictionary<string, obj>
          HasErrors = false; Errors = [] }

    /// Split the raw state dict (keyed with `__filter:` / `__gfn:` prefixes for
    /// filters and global functions) into the PrebuildResult buckets.
    let private splitResult (raw: IDictionary<string, obj>) (hasErrors: bool) (errors: string list) : PrebuildResult =
        let globals = Dictionary<string, obj>()
        let filters = Dictionary<string, string>()
        let globalFns = Dictionary<string, obj>()
        for kv in raw do
            if kv.Key.StartsWith("__filter:") then
                filters.[kv.Key.Substring(9)] <- toStr kv.Value
            elif kv.Key.StartsWith("__gfn:") then
                globalFns.[kv.Key.Substring(6)] <- kv.Value
            else
                globals.[kv.Key] <- kv.Value
        { GlobalData = globals :> IDictionary<string, obj>
          Filters = filters :> IDictionary<string, string>
          GlobalFunctions = globalFns :> IDictionary<string, obj>
          HasErrors = hasErrors; Errors = errors }

    /// Assemble and run one prebuild script.
    let private executeScript (rootDir: string) (scriptPath: string) : PrebuildResult =
        let label = FileTypes.PrebuildScriptFileName
        try
            let tmpResult =
                Path.Combine(Path.GetTempPath(), sprintf "zest-prebuild-%s.json" (Guid.NewGuid().ToString("N")))
            try
                let userScript = File.ReadAllText scriptPath
                let source = buildPreamble rootDir tmpResult + "\n" + userScript + "\n__writeResult ()"
                // The result file doubles as the completion marker: it is
                // written by the script's final statement, so a missing file
                // means the user code threw before finishing.
                let scriptRun = ScriptHost.runSource label tmpResult source
                if scriptRun.Succeeded then
                    splitResult (ScriptHost.readResultFile tmpResult) false []
                else
                    { emptyResult with HasErrors = true; Errors = [ scriptRun.ErrorText ] }
            finally
                try if File.Exists tmpResult then File.Delete tmpResult with _ -> ()
        with ex ->
            { emptyResult with
                HasErrors = true
                Errors = [ sprintf "%s failed: %s" label ex.Message ] }

    /// Run the _prebuild.fsx script (if present) and return the result.
    /// The script receives build inputs through its preamble, not as arguments.
    let run (rootDir: string) (_globalData: IDictionary<string, obj>) : PrebuildResult =
        match findPrebuildScript rootDir with
        | None -> emptyResult
        | Some prebuildPath -> executeScript rootDir prebuildPath
